function out1 = WindNoiseQuadrotorStateFcnBase(in1,in2,in3,in4)
%WindNoiseQuadrotorStateFcnBase
%    OUT1 = WindNoiseQuadrotorStateFcnBase(IN1,IN2,IN3,IN4)

%    This function was generated by the Symbolic Math Toolbox version 9.0.
%    16-Aug-2025 00:43:27

F_ext_x = in3(:,1);
F_ext_y = in3(:,2);
F_ext_z = in3(:,3);
T = in2(3,:);
g = in4(:,3);
k = in4(:,1);
m = in4(:,2);
omegaMax2 = in4(:,4);
phi = in2(1,:);
theta = in2(2,:);
u = in1(4,:);
v = in1(5,:);
w = in1(6,:);
t2 = cos(phi);
t3 = 1.0./m;
out1 = [u;v;w;t3.*(F_ext_x-T.*k.*omegaMax2.*t2.*sin(theta).*4.0);t3.*(F_ext_y+T.*k.*omegaMax2.*sin(phi).*4.0);t3.*(F_ext_z+g.*m-T.*k.*omegaMax2.*t2.*cos(theta).*4.0)];
